### ISSUE TITLE
RosBridgeClientUWP cannot connect to ros2 rosbridge server

### ISSUE THREAD

**Issue by cxiliu** [luchspeter/ros-sharp#21]
## I found a bug! ##
* [x] I am using the latest ROS# version available here on the master branch.
* [x] I am adding all required information, code and data files, screenshots and log files so that you can reproduce the problem.

* My OS is: Windows 10
* My Unity Version is: 2020.3.25
* My ROS Distribution is: ROS2 foxy
* My Build Target Platform is: ARM/HoloLens2

**Here is my bug description:**
I am using ros2 branch of the rosbridge server at https://github.com/RobotWebTools/rosbridge_suite. 
Ros-sharp library works perfectly with ros2 server from within the Unity editor (with small complaints on timestamp formatting https://github.com/siemens/ros-sharp/issues/315 but connection was not an issue). When I switch from Websocket Sharp/.NET to the UWP version to deploy it on HoloLens, connection cannot be established. 

Perform the following steps to reproduce the bug:
Build the demo unity project in ProjectSetup/RosSharpUnity (to either HoloLens1 or 2) and try to connect with the ros2 branch of rosbridge_websocket

Observed results:
Connection cannot be established (no useful information in the log, see attached snippet 
[UnityPlayer.log](https://github.com/EricVoll/ros-sharp/files/7840694/UnityPlayer.log) )

Expected results:
Connection established, as it did in the Unity editor

Thanks!

**Comment by EricVoll** [comment]
Hi @cxiliu 
This looks like a serialization / code-stripping issue.
I have no experience with ROS2 so far, so I can't really help out here.
Maybe try to disable Code-Stripping from the IL2CPP backend as described [here](https://docs.unity3d.com/2017.4/Documentation/Manual/IL2CPP-BytecodeStripping.html#:~:text=If%20it%20is%20disabled%2C%20all%20of%20the%20modules,stripped%2C%20the%20following%20link.xml%20file%20can%20be%20used%3A).
If it works after code stripping was disabled, then its "only" a matter of finding the right dll to exclude from code-stripping.
